# Generated by Django 5.2 on 2025-04-11 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeKeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village', models.CharField(max_length=100, verbose_name='Village')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('years_experience', models.PositiveIntegerField(verbose_name='Years of Experience')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Area of Specialization')),
                ('bio', models.TextField(blank=True, verbose_name='Biography')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_keeper', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Knowledge Keeper',
                'verbose_name_plural': 'Knowledge Keepers',
            },
        ),
        migrations.CreateModel(
            name='IndigenousKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('practice_type', models.CharField(choices=[('pest_control', 'Pest Control'), ('disease_management', 'Disease Management'), ('soil_fertility', 'Soil Fertility'), ('water_conservation', 'Water Conservation'), ('seed_preservation', 'Seed Preservation'), ('weather_prediction', 'Weather Prediction'), ('other', 'Other')], max_length=50, verbose_name='Practice Type')),
                ('materials', models.JSONField(default=list, verbose_name='Materials')),
                ('crops', models.JSONField(default=list, verbose_name='Applicable Crops')),
                ('pests', models.JSONField(blank=True, default=list, verbose_name='Target Pests')),
                ('seasons', models.JSONField(default=list, verbose_name='Applicable Seasons')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Verification Status')),
                ('verification_count', models.PositiveIntegerField(default=0, verbose_name='Verification Count')),
                ('keeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_entries', to='community.knowledgekeeper')),
            ],
            options={
                'verbose_name': 'Indigenous Knowledge',
                'verbose_name_plural': 'Indigenous Knowledge Entries',
            },
        ),
        migrations.CreateModel(
            name='RegionalObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('observation_type', models.CharField(choices=[('pest_outbreak', 'Pest Outbreak'), ('disease_occurrence', 'Disease Occurrence'), ('ecological_indicator', 'Ecological Indicator'), ('weather_pattern', 'Weather Pattern'), ('other', 'Other')], max_length=50, verbose_name='Observation Type')),
                ('village', models.CharField(max_length=100, verbose_name='Village')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('crops_affected', models.JSONField(blank=True, default=list, verbose_name='Crops Affected')),
                ('date_observed', models.DateField(verbose_name='Date Observed')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regional Observation',
                'verbose_name_plural': 'Regional Observations',
            },
        ),
        migrations.CreateModel(
            name='CommunityValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Rating')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('has_used', models.BooleanField(default=False, verbose_name='Has Used This Practice')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('validator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to=settings.AUTH_USER_MODEL)),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='community.indigenousknowledge')),
            ],
            options={
                'verbose_name': 'Community Validation',
                'verbose_name_plural': 'Community Validations',
                'unique_together': {('knowledge', 'validator')},
            },
        ),
        migrations.CreateModel(
            name='SesothoTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100, verbose_name='Sesotho Term')),
                ('english', models.CharField(max_length=100, verbose_name='English Translation')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('contributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_terms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesotho Term',
                'verbose_name_plural': 'Sesotho Terms',
                'unique_together': {('term', 'english')},
            },
        ),
    ]
