# Generated by Django 5.1.7 on 2025-04-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indigenousknowledge',
            name='is_exported',
            field=models.BooleanField(default=False, verbose_name='Is Exported'),
        ),
        migrations.AddField(
            model_name='indigenousknowledge',
            name='last_exported',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Exported'),
        ),
        migrations.AddField(
            model_name='indigenousknowledge',
            name='prolog_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Prolog Name'),
        ),
    ]
