# Generated by Django 5.1.7 on 2025-04-12 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_indigenousknowledge_is_exported_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('knowledge_keeper', 'Knowledge Keeper'), ('community_member', 'Community Member'), ('knowledge_seeker', 'Knowledge Seeker'), ('administrator', 'Administrator')], default='knowledge_seeker', max_length=50, verbose_name='User Role')),
                ('bio', models.TextField(blank=True, verbose_name='Biography')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
