# Generated by Django 4.2.7 on 2025-04-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityvalidation',
            name='has_used',
        ),
        migrations.RemoveField(
            model_name='regionalobservation',
            name='crops_affected',
        ),
        migrations.RemoveField(
            model_name='regionalobservation',
            name='district',
        ),
        migrations.RemoveField(
            model_name='regionalobservation',
            name='village',
        ),
        migrations.AddField(
            model_name='regionalobservation',
            name='location',
            field=models.CharField(default=1, max_length=200, verbose_name='Location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='communityvalidation',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Rating'),
        ),
        migrations.AddIndex(
            model_name='communityvalidation',
            index=models.Index(fields=['rating'], name='cv_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='communityvalidation',
            index=models.Index(fields=['date_added'], name='cv_date_added_idx'),
        ),
        migrations.AddIndex(
            model_name='indigenousknowledge',
            index=models.Index(fields=['title'], name='ik_title_idx'),
        ),
        migrations.AddIndex(
            model_name='indigenousknowledge',
            index=models.Index(fields=['practice_type'], name='ik_practice_type_idx'),
        ),
        migrations.AddIndex(
            model_name='indigenousknowledge',
            index=models.Index(fields=['verification_status'], name='ik_verification_status_idx'),
        ),
        migrations.AddIndex(
            model_name='indigenousknowledge',
            index=models.Index(fields=['date_added'], name='ik_date_added_idx'),
        ),
        migrations.AddIndex(
            model_name='indigenousknowledge',
            index=models.Index(fields=['date_modified'], name='ik_date_modified_idx'),
        ),
        migrations.AddIndex(
            model_name='indigenousknowledge',
            index=models.Index(fields=['is_exported'], name='ik_is_exported_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgekeeper',
            index=models.Index(fields=['village'], name='kk_village_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgekeeper',
            index=models.Index(fields=['district'], name='kk_district_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgekeeper',
            index=models.Index(fields=['specialization'], name='kk_specialization_idx'),
        ),
        migrations.AddIndex(
            model_name='regionalobservation',
            index=models.Index(fields=['observation_type'], name='ro_observation_type_idx'),
        ),
        migrations.AddIndex(
            model_name='regionalobservation',
            index=models.Index(fields=['location'], name='ro_location_idx'),
        ),
        migrations.AddIndex(
            model_name='regionalobservation',
            index=models.Index(fields=['date_observed'], name='ro_date_observed_idx'),
        ),
        migrations.AddIndex(
            model_name='regionalobservation',
            index=models.Index(fields=['date_added'], name='ro_date_added_idx'),
        ),
        migrations.AddIndex(
            model_name='sesothoterm',
            index=models.Index(fields=['term'], name='st_term_idx'),
        ),
        migrations.AddIndex(
            model_name='sesothoterm',
            index=models.Index(fields=['english'], name='st_english_idx'),
        ),
        migrations.AddIndex(
            model_name='sesothoterm',
            index=models.Index(fields=['date_added'], name='st_date_added_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='up_role_idx'),
        ),
    ]
