# Generated by Django 4.2.7 on 2025-04-18 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0004_remove_communityvalidation_has_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeKeeperApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village', models.CharField(max_length=100, verbose_name='Village')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('years_experience', models.PositiveIntegerField(verbose_name='Years of Experience')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Area of Specialization')),
                ('bio', models.TextField(blank=True, verbose_name='Biography')),
                ('reason', models.TextField(help_text='Why do you want to become a knowledge keeper?', verbose_name='Reason for Application')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('review_notes', models.TextField(blank=True, verbose_name='Review Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keeper_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Knowledge Keeper Application',
                'verbose_name_plural': 'Knowledge Keeper Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
