# Generated by Django 4.2.7 on 2025-04-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_knowledgekeeperapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityvalidation',
            name='has_used',
            field=models.BooleanField(default=False, help_text='Whether the validator has personally used or observed this practice', verbose_name='Has Used or Observed'),
        ),
    ]
