services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./pest-management-chatbot/farmlore-project:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    command: ["/app/start_web.sh"]
    environment:
      - DEBUG=True
      - SECRET_KEY=your_secret_key_here
      - DB_NAME=farmlore
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1] web nginx
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=tinyllama:latest
      - USE_OLLAMA=true
      - USE_PROLOG_PRIMARY=true
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_started
    healthcheck:
      test: ["CMD", "python", "/app/health_check.py", "--service", "web"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: always
    networks:
      - farmlore_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=farmlore
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - farmlore_network
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
      - static_volume:/usr/share/nginx/staticfiles
      - media_volume:/usr/share/nginx/media
    depends_on:
      - web
    restart: always
    networks:
      - farmlore_network
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./pest-management-chatbot/farmlore-project/healthcheck_ollama.sh:/healthcheck.sh
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: always
    healthcheck:
      test: ["CMD", "sh", "/healthcheck.sh"]
      interval: 30s
      timeout: 20s
      retries: 10
      start_period: 120s
    networks:
      - farmlore_network

volumes:
  postgres_data:
  static_volume:
  media_volume:
  ollama_data:

networks:
  farmlore_network:
    driver: bridge