% ========================
% COMMUNITY KNOWLEDGE BASE
% ========================
% This file is automatically generated from community contributions
% Last updated: 2025-04-12 21:20:17

% ========================
% HELPER PREDICATES
% ========================
% Find indigenous practices for controlling a specific pest
indigenous_practice_for_pest(Pest, Practice) :-
    practice(name:Practice, controls:Controls, cultural_context:Ctx),
    member(basotho, Ctx),
    member(Pest, Controls).

% Find indigenous practices for a specific crop
indigenous_practice_for_crop(Crop, Practice) :-
    practice(name:Practice, applicable_crops:Crops, cultural_context:Ctx),
    member(basotho, Ctx),
    member(Crop, Crops).

% Find verified indigenous practices (verification count >= 3)
verified_indigenous_practice(Practice) :-
    practice(name:Practice, verification_count:Count, cultural_context:Ctx),
    member(basotho, Ctx),
    Count >= 3.

% Find all indigenous practices by type
indigenous_practices_by_type(Type, Practices) :-
    findall(Practice, (
        practice(name:Practice, type:Type, cultural_context:Ctx),
        member(basotho, Ctx)
    ), Practices).

% Integrated queries that combine conventional and indigenous knowledge
all_practices_for_pest(Pest, AllPractices) :-
    findall(practice(Name, conventional), (
        practice(name:Name, controls:Controls, cultural_context:Ctx),
        \+ member(basotho, Ctx),
        member(Pest, Controls)
    ), ConventionalPractices),
    findall(practice(Name, indigenous), (
        practice(name:Name, controls:Controls, cultural_context:Ctx),
        member(basotho, Ctx),
        member(Pest, Controls)
    ), IndigenousPractices),
    append(ConventionalPractices, IndigenousPractices, AllPractices).
